#!/bin/sh
#
# .lessfilter - Custom rules for lesspipe
#

# activate the venv managing our Python lessfilters
. <LESSENV_ACTIVATE_PATH>

case "$1" in
    *.bcl)
        bcl_view.py "$1"
        ;;
    *.dcm)
        dicom_header.py "$1"
        ;;
    *)
        # We don't handle this format.
        exit 1
esac

# No further processing by lesspipe necessary
exit 0
